# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" "igb" ];
  boot.initrd.kernelModules = [ "igb" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/0357a60d-827b-4b6c-9290-7b974dd61b7f";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  boot.initrd.luks.devices."root".device = "/dev/disk/by-uuid/b26194e7-6e22-42f6-9fc2-3aa9f5974331";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/42D7-221F";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/0357a60d-827b-4b6c-9290-7b974dd61b7f";
      fsType = "btrfs";
      options = [ "subvol=@var" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/0357a60d-827b-4b6c-9290-7b974dd61b7f";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };
	
	fileSystems."/mnt/jellyfin-media" = {
		device = "/dev/mapper/jellyfin";
		fsType = "btrfs";
		options = [ "subvol=@" ];
	};
	
	fileSystems."/mnt/backup_jellyfin" = {
		device = "/dev/mapper/backup_jellyfin";
		fsType = "btrfs";
	};
	
	fileSystems."/mnt/backup_root" = {
		device = "/dev/mapper/backup_root";
		fsType = "btrfs";
	};

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
	#networking.useDHCP = lib.mkDefault true;
	networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;
	networking.interfaces.enp6s0 = {
		useDHCP = false;
		ipv4.addresses = [ {
			address = "169.168.1.1";
			prefixLength = 30;
		} ];
	};
	networking.interfaces.wlan0.useDHCP = lib.mkDefault true;
	networking.networkmanager.unmanaged = [ "interface-name:enp6s0" ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.bluetooth.enable = true; # enables support for Bluetooth
  hardware.bluetooth.powerOnBoot = true; # powers up the default Bluetooth controller on boot
  services.blueman.enable = true;
}
